name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Slack Export Data
        uses: actions/checkout@v3
        with:
          repository: noy/slowly-birds-log
          path: slack-export
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Convert Data
        env:
          SLACK_DATA_PATH: ./slack-export
        run: |
          node scripts/convert-data.js
          if [ ! -d "public/slack-data" ]; then
            echo "Error: public/slack-data directory was not created"
            exit 1
          fi

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist